//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public Admin()
        {
            this.Token_Admin = new HashSet<Token_Admin>();
        }
    
        public int Admin_Id { get; set; }
        public string Name { get; set; }
        public string User_Type { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Token_Admin> Token_Admin { get; set; }
    }
}
