//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blood_Bank
    {
        public Blood_Bank()
        {
            this.Donar_Info = new HashSet<Donar_Info>();
        }
    
        public int Id { get; set; }
        public string BGroup { get; set; }
        public string collection_Date { get; set; }
        public string Quantity { get; set; }
        public int Hid { get; set; }
    
        public virtual Hospital Hospital { get; set; }
        public virtual ICollection<Donar_Info> Donar_Info { get; set; }
    }
}
