//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public Doctor()
        {
            this.Appointments = new HashSet<Appointment>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Specaility { get; set; }
        public string Visiting_Hour { get; set; }
        public int Hid { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual Hospital Hospital { get; set; }
    }
}
