//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donar_Info
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Blood_group { get; set; }
        public string Phone { get; set; }
        public int Bid { get; set; }
    
        public virtual Blood_Bank Blood_Bank { get; set; }
    }
}
