//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HealthcareEntities : DbContext
    {
        public HealthcareEntities()
            : base("name=HealthcareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Ambulance> Ambulances { get; set; }
        public DbSet<Appointment> Appointments { get; set; }
        public DbSet<Blood_Bank> Blood_Bank { get; set; }
        public DbSet<Doctor> Doctors { get; set; }
        public DbSet<Donar_Info> Donar_Info { get; set; }
        public DbSet<Donate_Money> Donate_Money { get; set; }
        public DbSet<Hospital> Hospitals { get; set; }
        public DbSet<Medicine> Medicines { get; set; }
        public DbSet<Patient> Patients { get; set; }
    }
}
