//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospital
    {
        public Hospital()
        {
            this.Ambulances = new HashSet<Ambulance>();
            this.Blood_Bank = new HashSet<Blood_Bank>();
            this.Doctors = new HashSet<Doctor>();
            this.Medicines = new HashSet<Medicine>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
    
        public virtual ICollection<Ambulance> Ambulances { get; set; }
        public virtual ICollection<Blood_Bank> Blood_Bank { get; set; }
        public virtual ICollection<Doctor> Doctors { get; set; }
        public virtual ICollection<Medicine> Medicines { get; set; }
    }
}
